<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AnInfo.MailServer.Domain\AnInfo.MailServer.Domain.csproj" />
    <ProjectReference Include="..\AnInfo.MailServer.Application\AnInfo.MailServer.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.21"><PrivateAssets>all</PrivateAssets></PackageReference>
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="8.0.1" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
    <PackageReference Include="MimeKit" Version="4.17.0" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="SmtpServer" Version="11.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
