// <auto-generated />
using System;
using AnInfo.MailServer.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnInfo.MailServer.Infrastructure.Migrations
{
    [DbContext(typeof(MailDbContext))]
    [Migration("20260813222556_AddDeliveryAttempts")]
    partial class AddDeliveryAttempts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnInfo.MailServer.Domain.DeliveryAttempt", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ErrorType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MailMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("SmtpResponse")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int?>("SmtpStatusCode")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt");

                    b.HasIndex("MailMessageId", "AttemptNumber")
                        .IsUnique();

                    b.ToTable("DeliveryAttempts", (string)null);
                });

            modelBuilder.Entity("AnInfo.MailServer.Domain.MailMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<bool>("IsHtml")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)");

                    b.Property<DateTimeOffset?>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RawMime")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Subject")
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("Status", "CreatedAt");

                    b.HasIndex("Status", "NextAttemptAt");

                    b.ToTable("MailMessages", (string)null);
                });

            modelBuilder.Entity("AnInfo.MailServer.Domain.MailRecipient", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<Guid>("MailMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("MailMessageId");

                    b.ToTable("MailRecipients", (string)null);
                });

            modelBuilder.Entity("AnInfo.MailServer.Domain.DeliveryAttempt", b =>
                {
                    b.HasOne("AnInfo.MailServer.Domain.MailMessage", "MailMessage")
                        .WithMany("DeliveryAttempts")
                        .HasForeignKey("MailMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailMessage");
                });

            modelBuilder.Entity("AnInfo.MailServer.Domain.MailRecipient", b =>
                {
                    b.HasOne("AnInfo.MailServer.Domain.MailMessage", "MailMessage")
                        .WithMany("Recipients")
                        .HasForeignKey("MailMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MailMessage");
                });

            modelBuilder.Entity("AnInfo.MailServer.Domain.MailMessage", b =>
                {
                    b.Navigation("DeliveryAttempts");

                    b.Navigation("Recipients");
                });
#pragma warning restore 612, 618
        }
    }
}
